### ISSUE TITLE
Switch to `yarn` instead of `npm` for dependency management

### ISSUE THREAD

**Issue by jeffgran** [Bitcoin-com/Blockexplorer#1]
Yarn has better dependency management because it uses a lock file so we can guarantee that all local/production deploys use the same exact versions of everything as each other.

**Comment by robinkanters** [comment]
npm also uses lock files

**Comment by jeffgran** [comment]
I stand corrected. I've been on yarn for a while and didn't realize that npm caught up. Answer here has more context: https://stackoverflow.com/a/46352264

I'll close.
